# Generated by Django 5.2 on 2025-04-07 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='DOB',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='emailaddress@youremailserver.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_city',
            field=models.CharField(default='Enter City', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_state',
            field=models.CharField(default='Enter State', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(default='http://linkedin.com/yourprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spouse_DOB',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spouse_name',
            field=models.CharField(default='Please Enter', max_length=100),
        ),
    ]
