# Generated by Django 5.2 on 2025-04-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_dob_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_state',
            field=models.CharField(default='Unknown State', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(default='http://linkedin.com'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='spouse_name',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
